### ISSUE TITLE
[BUG]: creating an event returns a boolean and seems to succeed even when I would expect it to fail.

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago-ruby-client#13]
**Describe the bug**
I am testing sending events to Lago using this gem. I get a boolean response where I would expect a representation of the resource that was create or some kind of http response object. In addition, if I send an event with a `customer_id` that doesn't exist in Lago I get the same true response.

**To Reproduce**
```
client = Lago::Api::Client.new(api_key: ENV['LAGO_API_KEY'])
r = client.events.create(transaction_id: SecureRandom.uuid, customer_id: 2010, code: :mobilepay_transaction, properties: { donation_id: 12345 })
=> true
r = client.events.create(transaction_id: SecureRandom.uuid, customer_id: 20100000, code: :mobilepay_transaction, properties: { donation_id: 12345 })
=> true
```

**Expected behavior**
I expect the response to fail if the `customer_id` doesn't exist in Lago. I also expect to get either an HTTP response that I can check the status and headers of or a representation of the resource created by the API call.

**Comment by prognostikos** [comment]
I guess this is all by design, looking at the code for the client and the events api controller, but it is surprising.

**Comment by prognostikos** [comment]
I think it would be good to get an error if sending an invalid `code` or a `customer_id` that doesn't exist. I'm less concerned about transaction ID as it looks like the API endpoint will already not duplicate the event if the transaction id has been seen before.

An alternative could be that you keep the events endpoint asynchronous but send a webhook when an event is created so if needed we can subscribe to that notification to confirm creation. Basically, I want to be certain the event creation suceeded or know if there is a problem. Right now if I send an invalid `customer_id` or `code` the event creation service will fail but I won't have gotten any notification about it.

I guess another option could be a webhook sent only when event creation failed - that would presumably be triggered less often.

**Comment by jdenquin** [comment]
We discussed it a bit, and we think that sending a webhook error with the type `error` sounds like the best option!
We are scoping it and adding it to our roadmap

**Comment by sarkissianraffi** [comment]
We add this to the roadmap, prioritizing it for week 25. You can find the improvement issue [here](https://github.com/getlago/lago/issues/43)
