### ISSUE TITLE
[BUG]: error_code is a string, not an integer

### ISSUE THREAD

**Issue by prognostikos** [getlago/lago-ruby-client#17]
I guess this could be debatable if it is in fact a bug, but I think it is at least surprising.

In a `Lago::Api::HttpError`, the `#error_code` method returns a string, not an integer. This is apparently what `Net::Http` returns in its `response.code` method as it's the source of the value.

In every other ruby Http client that I've used (Faraday, Excon, etc) the code is an integer which allows matching against Rails' http symbols like `:not_found` etc.

Happy to provide a PR for this, either to change the type of the return value or at a minimum to document it in the README (or both)

**Comment by lovrocolic** [comment]
Hey @prognostikos,

Thanks for the issue raised.

It would be great if you can submit a PR for changing the type of `error_code`!
